download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", method="curl", destfile="exdata-data-household_power_consumption.zip")
unzip("exdata-data-household_power_consumption.zip")
test.semi <- read.table("household_power_consumption.txt",header = TRUE, sep = “;”, na.strings = "?", colClasses = c("factor",  "factor", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
test.semi$Date <- as.Date(test.semi$Date,format="%d/%m/%Y")
test.semi$Time <- strptime(test.semi$Time, format="%H:%M:%S")
data <- subset(test.semi, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
png("plot1.png")
hist(data$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)",ylab="Frequency")
dev.off()