png("plot4.png")
par(mfrow=c(2,2))
plot(x=subData$dateTime,y=subData$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(x=subData$dateTime,y=subData$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(subData$dateTime,subData$Sub_metering_1,type="n",xlab = "",ylab = "Energy sub metering")
lines(subData$dateTime,subData$Sub_metering_1)
lines(subData$dateTime,subData$Sub_metering_2,col="red")
lines(subData$dateTime,subData$Sub_metering_3,col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), col=c("black", "red", "blue"))
plot(x=subData$dateTime,y=subData$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()