png("plot3.png")
plot(subData$dateTime,subData$Sub_metering_1,type="n",xlab = "",ylab = "Energy sub metering")
lines(subData$dateTime,subData$Sub_metering_1)
lines(subData$dateTime,subData$Sub_metering_2,col="red")
lines(subData$dateTime,subData$Sub_metering_3,col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), col=c("black", "red", "blue"))
dev.off()